version: "3.9"
services:
  node:
    build: 
      dockerfile: dockerfile
      context: .
    image: node-orm:1.0
    container_name: node-orm
    restart: unless-stopped
    working_dir: /home/node/app/api
    networks:
      - api-sequelize
    ports:
      - "8080:8080"
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ./api/:/home/node/app/api
      - ./package-lock.json:/home/node/app/package-lock.json
      - ./package.json:/home/node/app/package.json
      - ./.eslintrc.json:/home/node/app/.eslintrc.json
    depends_on:
      - "mysql"

  mysql:
    image: mysql:8.0.28-oracle
    container_name: mysql-orm
    environment:
      MYSQL_ROOT_PASSWORD: abcdefg
      MYSQL_DATABASE: escola_ingles
      MYSQL_USER: node
      MYSQL_PASSWORD: abcdefg
      network_mode:   
    ports:
      - "3307:3306"
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      - api-sequelize

networks:
  api-sequelize:
    driver: bridge

volumes:
  mysql:
  mysql_config:
